# Generated by Django 4.2.7 on 2023-11-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('end_cep', models.CharField(max_length=8)),
                ('end_logradouro', models.CharField(max_length=255)),
                ('end_numero', models.CharField(max_length=10)),
                ('end_complemento', models.CharField(max_length=100)),
                ('end_bairro', models.CharField(max_length=100)),
                ('end_cidade', models.CharField(max_length=100)),
                ('end_uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField()),
                ('id_cliente', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.IntegerField()),
                ('id_pedido', models.IntegerField()),
                ('quantidade', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qt_estoque', models.IntegerField()),
            ],
        ),
    ]
