# Generated by Django 4.2.7 on 2023-11-26 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sispao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispao.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoprodutos',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispao.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoprodutos',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispao.produto'),
        ),
    ]
